source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'Drafter_Example', :exclusive => true do
    pod "Drafter", :path => "../"
end

target 'Drafter_Tests', :exclusive => true do
    pod "Drafter", :path => "../"

    pod 'Quick', :git => 'git@github.com:Quick/Quick.git', :branch => 'swift-2.0'
    pod 'Nimble', :git => 'git@github.com:Quick/Nimble.git', :branch => 'swift-2.0'
end
