source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'TailoredSwiftAutoLayoutHelpers_Example', :exclusive => true do
  pod "TailoredSwiftAutoLayoutHelpers", :path => "../"
end

target 'TailoredSwiftAutoLayoutHelpers_Tests', :exclusive => true do
  pod "TailoredSwiftAutoLayoutHelpers", :path => "../"

  pod 'Nimble', :git => 'https://github.com/Quick/Nimble.git', :branch => 'swift-2.0'

end
