source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'TailoredSwiftAutoLayoutHelpers_Example', :exclusive => true do
  pod "TailoredSwiftAutoLayoutHelpers", :path => "../"
end

target 'TailoredSwiftAutoLayoutHelpers_Tests', :exclusive => true do
  pod "TailoredSwiftAutoLayoutHelpers", :path => "../"

  pod 'Quick', '~> 0.3.1'
  pod 'Nimble'
end
